ARG FEDORA_VERSION="${FEDORA_VERSION:-42}"
ARG IMAGE_VERSION="${IMAGE_VERSION:-stable}"
ARG UCORE_VERSION="${UCORE_VERSION:-stable}"

FROM scratch AS ctx

ARG HELM_BINARY_URL="${HELM_BINARY_URL}"

COPY / /
ADD --chmod=755 ${HELM_BINARY_URL} /

# u3s-minimal image section
FROM ghcr.io/ublue-os/ucore-minimal:${UCORE_VERSION} AS u3s

ARG UCORE_VERSION="${UCORE_VERSION:-stable}"
ARG K3S_VERSION="${K3S_VERSION}"
ARG K3S_BINARY_URL="${K3S_BINARY_URL}"
ARG K3S_BINARY_DIGEST="${K3S_BINARY_DIGEST}"
ARG K8S_VERSION="${K8S_VERSION}"
ARG CRIO_VERSION="${CRIO_VERSION}"
ARG CALICO_VERSION="${CALICO_VERSION:-latest}"
ARG CALICO_BINARY_URL="${CALICO_BINARY_URL}"
ARG HELM_BINARY_TARBALL="${HELM_BINARY_TARBALL}"

COPY system_files/etc /etc

# Leaving here for knowledge...
# See: https://github.com/redhat-actions/buildah-build/issues/142
#ADD --chmod=755 --checksum=${K3S_BINARY_DIGEST} ${K3S_BINARY_URL} /usr/bin/
ADD --chmod=755 ${K3S_BINARY_URL} /usr/bin/
ADD --chmod=755 ${CALICO_BINARY_URL} /usr/bin/

RUN --mount=type=cache,dst=/var/cache/libdnf5 \
    --mount=type=cache,dst=/var/cache/rpm-ostree \
    --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/install-u3s.sh \
    && /ctx/post-install-u3s.sh \
    && /ctx/cleanup.sh
    
RUN ["bootc", "container", "lint"]