name: stable-nvidia
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: '55 2 * * *'  # 2:55am-ish UTC everyday (approx 50 minutes after akmods images run)
  workflow_dispatch:

jobs:
  build-stable-nvidia:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      ucore_version: stable-nvidia